#!/usr/bin/env python3
"""Assemble the self-contained CDM delivery (two files, in-repo, no shared repo, no external DB):
  cdm_load/cdm_ddl.sql   — the schema DDL (static, authored to the live column set; not touched here)
  cdm_load/cdm_load.sql  — the load: concept seed -> staging (person/visit) -> map-driven facts

Regenerates the generated pieces first: staging (06_render), concept seed (08), facts (09; gate/--all),
then concatenates them into cdm_load.sql. The map-driven ETL already writes the corrected pron/sup
concepts from the maps, so no post-load correction is appended.

  python scripts/10_build_cdm_delivery.py            # approved-only facts (default)
  python scripts/10_build_cdm_delivery.py --all       # dev override: all maps
"""
import argparse, os, subprocess, sys
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CDML = os.path.join(ROOT, "cdm_load")

def run(script, *args):
    print(f"  $ python scripts/{script} {' '.join(args)}".rstrip())
    subprocess.run([sys.executable, os.path.join(ROOT, "scripts", script), *args], cwd=ROOT, check=True)

def main():
    ap = argparse.ArgumentParser(); ap.add_argument("--all", action="store_true"); a = ap.parse_args()
    print("== 1/6 staging  (06_render_cdm_load.py) =="); run("06_render_cdm_load.py")
    print("== 2/6 concept seed  (08_concept_seed.py) =="); run("08_concept_seed.py")
    print("== 3/6 map-driven facts  (09_map_etl.py) =="); run("09_map_etl.py", *(["--all"] if a.all else []))
    print("== 4/6 extensions  (11_render_extensions.py) =="); run("11_render_extensions.py")
    print("== 5/6 governance  (12_render_governance.py) =="); run("12_render_governance.py")
    print("== 6/6 assemble cdm_load/cdm_load.sql ==")
    # FK-safe order: concept -> staging(person/visit) -> facts(obs/meas) -> extensions(specimen/assay/files)
    #                -> governance ACLs -> RLS enable/force + policies (must be last).
    parts = ["concept_seed.sql", "01_staging_and_structure.sql", "cdm_facts_load.sql",
             "extensions_load.sql", "governance_load.sql", "governance_rls.sql"]
    out = os.path.join(CDML, "cdm_load.sql")
    with open(out, "w", encoding="utf-8") as f:
        f.write("-- GENERATED by scripts/10_build_cdm_delivery.py — SELF-CONTAINED CDM load.\n")
        f.write("-- Run cdm_load/cdm_ddl.sql (schema) FIRST, then this file.\n")
        f.write("-- Pieces, in FK-safe order: concept seed -> staging (person/visit) -> map-driven facts.\n")
        f.write("\\set ON_ERROR_STOP on\n")
        for p in parts:
            f.write(f"\n\\echo '################  {p}  ################'\n")
            f.write(open(os.path.join(CDML, p), encoding="utf-8").read().rstrip() + "\n")
    print(f"\nwrote {os.path.relpath(out, ROOT)}  ({os.path.getsize(out)//1024} KB)")
    print(f"DELIVERY: cdm_load/cdm_ddl.sql (schema) + cdm_load/cdm_load.sql "
          f"({'ALL maps' if a.all else 'approved-only'})  — build with cdm_load/build_selfcontained.sh")

if __name__ == "__main__":
    main()
