#!/usr/bin/env python3
"""Render the CDM extension load -> cdm_load/extensions_load.sql (COPY FROM stdin; self-contained).
Reads ONLY output/*.csv + inputs/biospecimen_type_crosswalk.tsv. No DB. Deterministic.
Emits: cdm.specimen (AD tissue + RA-SLE biospecimen, concept via crosswalk), cdm.assay, cdm.files,
cdm.assay_to_specimen, cdm.assay_input_file. Surrogate ids are the deterministic ids minted in gen.
person_id == participant_id (staging.person_map is identity). Run AFTER concept_seed + staging + facts.
"""
import csv, io, os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT  = os.path.join(ROOT, "output")
SQL  = os.path.join(ROOT, "cdm_load", "extensions_load.sql")
PROGS = ["AMP-AD", "AMP-RA-SLE"]
SPECIMEN_DATE = "2016-06-01"     # synthetic collection date (not governance-relevant); constant = deterministic
SPECIMEN_TYPE = 32817            # OMOP type concept 'EHR' (the pipeline's type concept)
# specimen-derivation lineage -> cdm.fact_relationship: OMOP 'Specimen' domain + a bidirectional derivation pair.
SPECIMEN_DOMAIN          = 36     # 'Specimen' domain concept (fact_relationship.domain_concept_id_*)
REL_SUBSPECIMEN_OF       = 32554  # child -> parent ('Sub-specimen of')
REL_INCLUDES_SUBSPECIMEN = 32553  # parent -> child ('Includes sub-specimen')

def rd(name):
    p = os.path.join(OUT, name)
    return list(csv.DictReader(open(p, newline="", encoding="utf-8"))) if os.path.exists(p) else []

def crosswalk():
    lines = [l for l in open(os.path.join(ROOT, "inputs", "biospecimen_type_crosswalk.tsv"), encoding="utf-8")
             if not l.startswith("#")]
    return {r["source_value"]: int(r["specimen_concept_id"])
            for r in csv.DictReader(io.StringIO("".join(lines)), delimiter="\t")}

def esc(v):
    if v is None or v == "": return "\\N"
    return str(v).replace("\\", "\\\\").replace("\t", " ").replace("\n", " ").replace("\r", " ")

def copy_block(f, table, cols, rows):
    if not rows: return 0
    f.write(f"COPY cdm.{table} ({', '.join(cols)}) FROM stdin;\n")
    for r in rows:
        f.write("\t".join(esc(r.get(c.strip(chr(34)))) for c in cols) + "\n")
    f.write("\\.\n\n")
    return len(rows)

def main():
    xw = crosswalk()
    def concept_for(v): return xw.get(v, 0)
    specimens, assays, files, a2s, aif = [], [], [], [], []
    lineage_pairs = []   # (child_specimen_id, parent_specimen_id) from RA-SLE parentBiospecimenID

    for prog in PROGS:
        # specimen: AMP-AD from *_specimen.csv (tissue); AMP-RA-SLE from the ARK specimen CSV (biospecimenType)
        if prog == "AMP-AD":
            for r in rd("AMP-AD_specimen.csv"):
                specimens.append({"specimen_id": r["specimen_id"], "person_id": r["participant_id"],
                    "specimen_concept_id": concept_for(r["specimen_source_value"]),
                    "specimen_type_concept_id": SPECIMEN_TYPE, "specimen_date": SPECIMEN_DATE,
                    "specimen_source_id": r["specimen_id"], "specimen_source_value": r["specimen_source_value"],
                    "anatomic_site_source_value": r.get("anatomic_site_source_value") or ""})
        else:
            for r in rd("AMP-RA-SLE_specimen.csv"):
                bid = r.get("biospecimenID")
                if not bid: continue
                specimens.append({"specimen_id": bid, "person_id": r["participant_id"],
                    "specimen_concept_id": concept_for(r.get("biospecimenType") or ""),
                    "specimen_type_concept_id": SPECIMEN_TYPE, "specimen_date": SPECIMEN_DATE,
                    "specimen_source_id": bid, "specimen_source_value": r.get("biospecimenType") or "",
                    "anatomic_site_source_value": r.get("anatomicalSite") or ""})
                parent = (r.get("parentBiospecimenID") or "").strip()
                if parent:
                    lineage_pairs.append((bid, parent))
        assays += rd(f"{prog}_assay.csv")
        files  += rd(f"{prog}_file.csv")
        a2s    += rd(f"{prog}_assay_to_specimen.csv")
        aif    += rd(f"{prog}_assay_input_file.csv")

    # specimen derivation lineage -> cdm.fact_relationship (bidirectional; RA-SLE parent links, AD single-autopsy).
    spec_ids = {s["specimen_id"] for s in specimens}
    frels = []
    for child, parent in lineage_pairs:
        if child in spec_ids and parent in spec_ids:
            frels.append({"domain_concept_id_1": SPECIMEN_DOMAIN, "fact_id_1": child,
                          "domain_concept_id_2": SPECIMEN_DOMAIN, "fact_id_2": parent,
                          "relationship_concept_id": REL_SUBSPECIMEN_OF})
            frels.append({"domain_concept_id_1": SPECIMEN_DOMAIN, "fact_id_1": parent,
                          "domain_concept_id_2": SPECIMEN_DOMAIN, "fact_id_2": child,
                          "relationship_concept_id": REL_INCLUDES_SUBSPECIMEN})

    with open(SQL, "w", encoding="utf-8") as f:
        f.write("-- GENERATED by scripts/11_render_extensions.py — CDM extension load (specimen/assay/files).\n")
        f.write("-- Self-contained; reads no DB. Run after concept_seed + staging + facts.\n")
        f.write("SET search_path = cdm, public;\n\n")
        ns = copy_block(f, "specimen",
            ["specimen_id","person_id","specimen_concept_id","specimen_type_concept_id","specimen_date",
             "specimen_source_id","specimen_source_value","anatomic_site_source_value"], specimens)
        nfr = copy_block(f, "fact_relationship",
            ["domain_concept_id_1","fact_id_1","domain_concept_id_2","fact_id_2","relationship_concept_id"], frels)
        na = copy_block(f, "assay",
            ["assay_id","assay_source_value","assay_type","platform","suspension_type","analyte_type","analysis_pipeline"], assays)
        nf = copy_block(f, "files",
            ["file_id","file_name","assay_id","file_role","study","\"grant\"","analysis_type","biosample_type",
             "tissue","cell_type","species","file_format","file_size_bytes","drs_id"],
            [{**r, "grant": r.get("grant")} for r in files])
        n2 = copy_block(f, "assay_to_specimen", ["assay_id","specimen_id"], a2s)
        ni = copy_block(f, "assay_input_file", ["assay_id","file_id"], aif)
    print(f"extensions_load.sql: specimen={ns} fact_relationship={nfr} assay={na} files={nf} assay_to_specimen={n2} assay_input_file={ni}")

if __name__ == "__main__":
    main()
