#!/usr/bin/env python3
"""Render the governance load -> cdm_load/governance_load.sql (COPY + INSERT..SELECT; self-contained).

Reads ONLY config/access_groups.tsv + output/*_subject.csv. No DB. Deterministic (constant timestamps).
Emits, in FK-safe order:
  cdm.access_groups          (one row per AMP program, from config/access_groups.tsv)
  cdm.user_access_groups     (SYNTHETIC TEST ROLES — the minimum to exercise RLS; not AMP policy)
  a TEMP _person_program     (person_id -> its program's access_group_id, from the subject CSVs)
  cdm.file_access            file-driven: files.study -> the matching program group
  cdm.specimen_access        file-first (specimen -> assay_to_specimen -> assay -> files group), else person program
  cdm.observation_access     person's program group (demographic obs are governed => data-free person is safe)
  cdm.measurement_access     person's program group
  cdm.procedure_occurrence_access  person's program group (no-op if no procedure rows are loaded)

Access model (approved): a row WITH a file takes that file's group; a row WITHOUT a file takes its
person's PROGRAM group. Only real signals are used; nothing invented. Run AFTER extensions_load.sql
(needs cdm.files / cdm.specimen loaded) and AFTER the facts load (needs cdm.observation / cdm.measurement).
governance_rls.sql (ENABLE/FORCE RLS + policies + roles) runs AFTER this file.
"""
import csv, io, os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT  = os.path.join(ROOT, "output")
SQL  = os.path.join(ROOT, "cdm_load", "governance_load.sql")
AG   = os.path.join(ROOT, "config", "access_groups.tsv")

CREATED_AT = "2016-06-01 00:00:00"   # constant => byte-deterministic (never now())
GRANTED_AT = "2016-06-01 00:00:00"
GRANTED_BY = "system"

# program label -> its subject CSV (the person->program signal). The program is the file name's, not a column.
SUBJECT_FILES = {"AMP-PD": "AMP-PD_subject.csv", "AMP-AD": "AMP-AD_subject.csv",
                 "AMP-CMD": "AMP-CMD_subject.csv", "AMP-RA-SLE": "AMP-RA-SLE_subject.csv"}

# SYNTHETIC test roles (fixtures to exercise RLS): role -> list of programs it may access.
# no_access_user gets NO grant on purpose (the negative control). Not AMP access policy.
ROLE_GRANTS = {
    "ad_user":          ["AMP-AD"],
    "rasle_user":       ["AMP-RA-SLE"],
    "consortium_admin": ["AMP-PD", "AMP-AD", "AMP-CMD", "AMP-RA-SLE"],
}

AG_COLS = ["id", "code", "name", "description", "program", "disease_focus", "dul", "data_access_instructions"]


def read_access_groups():
    lines = [l for l in open(AG, encoding="utf-8") if not l.startswith("#")]
    return list(csv.DictReader(io.StringIO("".join(lines)), delimiter="\t"))


def esc(v):
    if v is None or v == "":
        return "\\N"
    return str(v).replace("\\", "\\\\").replace("\t", " ").replace("\n", " ").replace("\r", " ")


def main():
    groups = read_access_groups()
    prog2id = {g["program"]: int(g["id"]) for g in groups}

    # person_id -> program group id, from every program's subject CSV (participant_id is globally unique).
    person_prog = {}
    for prog, fname in SUBJECT_FILES.items():
        p = os.path.join(OUT, fname)
        if not os.path.exists(p):
            continue
        gid = prog2id[prog]
        for r in csv.DictReader(open(p, newline="", encoding="utf-8")):
            person_prog[int(r["participant_id"])] = gid

    with open(SQL, "w", encoding="utf-8") as f:
        f.write("-- GENERATED by scripts/12_render_governance.py — record-level access governance load.\n")
        f.write("-- Self-contained; reads no DB. Run AFTER extensions_load.sql + the facts load; RLS runs after this.\n")
        f.write("SET search_path = cdm, public;\n\n")

        # 1) access_groups (created_at constant appended)
        f.write(f"COPY cdm.access_groups ({', '.join(AG_COLS)}, created_at) FROM stdin;\n")
        for g in groups:
            f.write("\t".join(esc(g.get(c)) for c in AG_COLS) + f"\t{CREATED_AT}\n")
        f.write("\\.\n\n")

        # 2) user_access_groups (synthetic test roles; one row per role x granted program)
        f.write("-- SYNTHETIC test roles (RLS fixtures; not AMP access policy). no_access_user gets no grant.\n")
        f.write("COPY cdm.user_access_groups (user_id, access_group_id, granted_at, granted_by) FROM stdin;\n")
        for role, progs in ROLE_GRANTS.items():
            for prog in progs:
                f.write(f"{role}\t{prog2id[prog]}\t{GRANTED_AT}\t{GRANTED_BY}\n")
        f.write("\\.\n\n")

        # 3) person -> program group (TEMP; drives the program-fallback ACLs)
        f.write("CREATE TEMP TABLE _person_program (person_id integer PRIMARY KEY, access_group_id integer NOT NULL);\n")
        f.write("COPY _person_program (person_id, access_group_id) FROM stdin;\n")
        for pid in sorted(person_prog):
            f.write(f"{pid}\t{person_prog[pid]}\n")
        f.write("\\.\n\n")

        # 4) file_access — file-driven: files.study -> matching program group
        f.write("-- file_access: file-driven (files.study -> the program's group)\n")
        f.write("INSERT INTO cdm.file_access (file_id, access_group_id)\n"
                "SELECT f.file_id, ag.id\n"
                "  FROM cdm.files f JOIN cdm.access_groups ag ON ag.program = f.study\n"
                "ON CONFLICT DO NOTHING;\n\n")

        # 5) specimen_access — file-first (via assay_to_specimen -> assay -> files), else person program
        f.write("-- specimen_access: file-first (specimen -> assay_to_specimen -> assay -> files group), else person program\n")
        f.write("INSERT INTO cdm.specimen_access (specimen_id, access_group_id)\n"
                "SELECT DISTINCT s.specimen_id, COALESCE(fg.grp, pp.access_group_id)\n"
                "  FROM cdm.specimen s\n"
                "  JOIN _person_program pp ON pp.person_id = s.person_id\n"
                "  LEFT JOIN LATERAL (\n"
                "    SELECT ag.id AS grp\n"
                "      FROM cdm.assay_to_specimen a2s\n"
                "      JOIN cdm.files f ON f.assay_id = a2s.assay_id\n"
                "      JOIN cdm.access_groups ag ON ag.program = f.study\n"
                "     WHERE a2s.specimen_id = s.specimen_id\n"
                "     LIMIT 1\n"
                "  ) fg ON true\n"
                "ON CONFLICT DO NOTHING;\n\n")

        # 6) observation / measurement / procedure — person's program group (no file link)
        for tbl, idcol in [("observation", "observation_id"),
                           ("measurement", "measurement_id"),
                           ("procedure_occurrence", "procedure_occurrence_id")]:
            f.write(f"-- {tbl}_access: person's program group\n")
            f.write(f"INSERT INTO cdm.{tbl}_access ({idcol}, access_group_id)\n"
                    f"SELECT t.{idcol}, pp.access_group_id\n"
                    f"  FROM cdm.{tbl} t JOIN _person_program pp ON pp.person_id = t.person_id\n"
                    f"ON CONFLICT DO NOTHING;\n\n")

    print(f"governance_load.sql: access_groups={len(groups)} "
          f"grants={sum(len(v) for v in ROLE_GRANTS.values())} persons={len(person_prog)}")


if __name__ == "__main__":
    main()
